services:
  - type: web
    name: lab3-expenses-api
    env: python
    plan: free
    region: frankfurt
    rootDir: "OneDrive/Рабочий стол/5 Семестр/БЕК/lab3"
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python -m flask db upgrade
    startCommand: gunicorn 'app.main:app' --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: FLASK_APP
        value: app.main:app
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: DATABASE_URL
        fromDatabase:
          name: lab3-postgres
          property: connectionString

databases:
  - name: lab3-postgres
    plan: free
    region: frankfurt
